### Register
POST {{baseUrl}}/auth/register
Content-Type: application/json
Accept: application/json

{
  "username": "{{username}}",
  "email": "{{email}}",
  "password": "{{password}}"
}

### Login
POST {{baseUrl}}/auth/login
Content-Type: application/json
Accept: application/json

{
  "email": "{{email}}",
  "password": "{{password}}"
}