class_name WsMessageType
extends RefCounted

# Client -> Server
const PING := "PING"
const CREATE_DEMO_SESSION := "CREATE_DEMO_SESSION"
const CANCEL_MARKET_OFFER := "CANCEL_MARKET_OFFER"

const CREATE_LOBBY := "CREATE_LOBBY"
const JOIN_LOBBY := "JOIN_LOBBY"
const LEAVE_LOBBY := "LEAVE_LOBBY"
const START_SESSION := "START_SESSION"

const BUILD_BUILDING := "BUILD_BUILDING"
const UPGRADE_BUILDING := "UPGRADE_BUILDING"
const COLLECT_BUILDING := "COLLECT_BUILDING"
const RECYCLE_RESOURCE := "RECYCLE_RESOURCE"

const GET_MARKET_STATE := "GET_MARKET_STATE"
const CREATE_MARKET_OFFER := "CREATE_MARKET_OFFER"
const ACCEPT_MARKET_OFFER := "ACCEPT_MARKET_OFFER"

const DEV_SEED_BOT_OFFER := "DEV_SEED_BOT_OFFER"
const DEV_FORCE_FINISH_SESSION := "DEV_FORCE_FINISH_SESSION"

# Server -> Client
const PONG := "PONG"
const SESSION_CREATED := "SESSION_CREATED"
const SESSION_STATE := "SESSION_STATE"
const LOBBY_STATE := "LOBBY_STATE"
const SESSION_CANCELLED := "SESSION_CANCELLED"
const OFFER_CANCELLED := "OFFER_CANCELLED"

const MARKET_STATE := "MARKET_STATE"
const OFFER_CREATED := "OFFER_CREATED"
const TRADE_COMPLETED := "TRADE_COMPLETED"
const RESOURCE_RECYCLED := "RESOURCE_RECYCLED"

const DEV_BOT_OFFER_CREATED := "DEV_BOT_OFFER_CREATED"
const GAME_FINISHED := "GAME_FINISHED"

const AUTHENTICATED := "AUTHENTICATED"
const ERROR := "ERROR"
